create database stock; 
use stock; 

-- create stock daily data table
CREATE TABLE `daily` (
  `trade_date` varchar(20) DEFAULT NULL,
  `ts_code` varchar(20) DEFAULT NULL,
  `open` double DEFAULT NULL,
  `high` double DEFAULT NULL,
  `low` double DEFAULT NULL,
  `close` double DEFAULT NULL,
  `pre_close` double DEFAULT NULL,
  `change` double DEFAULT NULL,
  `pct_chg` double DEFAULT NULL,
  `vol` double DEFAULT NULL,
  `amount` double DEFAULT NULL,
  UNIQUE KEY `idx_daily_trade_date_ts_code` (`ts_code`,`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- create income table 
CREATE TABLE `income` (
  `ts_code` varchar(20),
  `end_date` varchar(20),
  `ann_date` varchar(20),
  `f_ann_date` varchar(20),
  `report_type` varchar(10),
  `comp_type` varchar(10),
  `basic_eps` double DEFAULT NULL,
  `diluted_eps` double DEFAULT NULL,
  `total_revenue` double DEFAULT NULL,
  `revenue` double DEFAULT NULL,
  `int_income` double DEFAULT NULL,
  `prem_earned` double DEFAULT NULL,
  `comm_income` double DEFAULT NULL,
  `n_commis_income` double DEFAULT NULL,
  `n_oth_income` double DEFAULT NULL,
  `n_oth_b_income` double DEFAULT NULL,
  `prem_income` double DEFAULT NULL,
  `out_prem` double DEFAULT NULL,
  `une_prem_reser` double DEFAULT NULL,
  `reins_income` double DEFAULT NULL,
  `n_sec_tb_income` double DEFAULT NULL,
  `n_sec_uw_income` double DEFAULT NULL,
  `n_asset_mg_income` double DEFAULT NULL,
  `oth_b_income` double DEFAULT NULL,
  `fv_value_chg_gain` double DEFAULT NULL,
  `invest_income` double DEFAULT NULL,
  `ass_invest_income` double DEFAULT NULL,
  `forex_gain` double DEFAULT NULL,
  `total_cogs` double DEFAULT NULL,
  `oper_cost` double DEFAULT NULL,
  `int_exp` double DEFAULT NULL,
  `comm_exp` double DEFAULT NULL,
  `biz_tax_surchg` double DEFAULT NULL,
  `sell_exp` double DEFAULT NULL,
  `admin_exp` double DEFAULT NULL,
  `fin_exp` double DEFAULT NULL,
  `assets_impair_loss` double DEFAULT NULL,
  `prem_refund` double DEFAULT NULL,
  `compens_payout` double DEFAULT NULL,
  `reser_insur_liab` double DEFAULT NULL,
  `div_payt` double DEFAULT NULL,
  `reins_exp` double DEFAULT NULL,
  `oper_exp` double DEFAULT NULL,
  `compens_payout_refu` double DEFAULT NULL,
  `insur_reser_refu` double DEFAULT NULL,
  `reins_cost_refund` double DEFAULT NULL,
  `other_bus_cost` double DEFAULT NULL,
  `operate_profit` double DEFAULT NULL,
  `non_oper_income` double DEFAULT NULL,
  `non_oper_exp` double DEFAULT NULL,
  `nca_disploss` double DEFAULT NULL,
  `total_profit` double DEFAULT NULL,
  `income_tax` double DEFAULT NULL,
  `n_income` double DEFAULT NULL,
  `n_income_attr_p` double DEFAULT NULL,
  `minority_gain` double DEFAULT NULL,
  `oth_compr_income` double DEFAULT NULL,
  `t_compr_income` double DEFAULT NULL,
  `compr_inc_attr_p` double DEFAULT NULL,
  `compr_inc_attr_m_s` double DEFAULT NULL,
  `ebit` double DEFAULT NULL,
  `ebitda` double DEFAULT NULL,
  `insurance_exp` double DEFAULT NULL,
  `undist_profit` double DEFAULT NULL,
  `distable_profit` double DEFAULT NULL,
  UNIQUE KEY `idx_income_end_date_ts_code_report_type` (`ts_code`,`end_date`,`report_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- create balance table
CREATE TABLE `balance` (
  `ts_code` varchar(20),
  `end_date` varchar(20),
  `ann_date` varchar(20),
  `f_ann_date` varchar(20),
  `report_type` varchar(10),
  `comp_type` varchar(10),
  `total_share` double DEFAULT NULL,
  `cap_rese` double DEFAULT NULL,
  `undistr_porfit` double DEFAULT NULL,
  `surplus_rese` double DEFAULT NULL,
  `special_rese` double DEFAULT NULL,
  `money_cap` double DEFAULT NULL,
  `trad_asset` double DEFAULT NULL,
  `notes_receiv` double DEFAULT NULL,
  `accounts_receiv` double DEFAULT NULL,
  `oth_receiv` double DEFAULT NULL,
  `prepayment` double DEFAULT NULL,
  `div_receiv` double DEFAULT NULL,
  `int_receiv` double DEFAULT NULL,
  `inventories` double DEFAULT NULL,
  `amor_exp` double DEFAULT NULL,
  `nca_within_1y` double DEFAULT NULL,
  `sett_rsrv` double DEFAULT NULL,
  `loanto_oth_bank_fi` double DEFAULT NULL,
  `premium_receiv` double DEFAULT NULL,
  `reinsur_receiv` double DEFAULT NULL,
  `reinsur_res_receiv` double DEFAULT NULL,
  `pur_resale_fa` double DEFAULT NULL,
  `oth_cur_assets` double DEFAULT NULL,
  `total_cur_assets` double DEFAULT NULL,
  `fa_avail_for_sale` double DEFAULT NULL,
  `htm_invest` double DEFAULT NULL,
  `lt_eqt_invest` double DEFAULT NULL,
  `invest_real_estate` double DEFAULT NULL,
  `time_deposits` double DEFAULT NULL,
  `oth_assets` double DEFAULT NULL,
  `lt_rec` double DEFAULT NULL,
  `fix_assets` double DEFAULT NULL,
  `cip` double DEFAULT NULL,
  `const_materials` double DEFAULT NULL,
  `fixed_assets_disp` double DEFAULT NULL,
  `produc_bio_assets` double DEFAULT NULL,
  `oil_and_gas_assets` double DEFAULT NULL,
  `intan_assets` double DEFAULT NULL,
  `r_and_d` double DEFAULT NULL,
  `goodwill` double DEFAULT NULL,
  `lt_amor_exp` double DEFAULT NULL,
  `defer_tax_assets` double DEFAULT NULL,
  `decr_in_disbur` double DEFAULT NULL,
  `oth_nca` double DEFAULT NULL,
  `total_nca` double DEFAULT NULL,
  `cash_reser_cb` double DEFAULT NULL,
  `depos_in_oth_bfi` double DEFAULT NULL,
  `prec_metals` double DEFAULT NULL,
  `deriv_assets` double DEFAULT NULL,
  `rr_reins_une_prem` double DEFAULT NULL,
  `rr_reins_outstd_cla` double DEFAULT NULL,
  `rr_reins_lins_liab` double DEFAULT NULL,
  `rr_reins_lthins_liab` double DEFAULT NULL,
  `refund_depos` double DEFAULT NULL,
  `ph_pledge_loans` double DEFAULT NULL,
  `refund_cap_depos` double DEFAULT NULL,
  `indep_acct_assets` double DEFAULT NULL,
  `client_depos` double DEFAULT NULL,
  `client_prov` double DEFAULT NULL,
  `transac_seat_fee` double DEFAULT NULL,
  `invest_as_receiv` double DEFAULT NULL,
  `total_assets` double DEFAULT NULL,
  `lt_borr` double DEFAULT NULL,
  `st_borr` double DEFAULT NULL,
  `cb_borr` double DEFAULT NULL,
  `depos_ib_deposits` double DEFAULT NULL,
  `loan_oth_bank` double DEFAULT NULL,
  `trading_fl` double DEFAULT NULL,
  `notes_payable` double DEFAULT NULL,
  `acct_payable` double DEFAULT NULL,
  `adv_receipts` double DEFAULT NULL,
  `sold_for_repur_fa` double DEFAULT NULL,
  `comm_payable` double DEFAULT NULL,
  `payroll_payable` double DEFAULT NULL,
  `taxes_payable` double DEFAULT NULL,
  `int_payable` double DEFAULT NULL,
  `div_payable` double DEFAULT NULL,
  `oth_payable` double DEFAULT NULL,
  `acc_exp` double DEFAULT NULL,
  `deferred_inc` double DEFAULT NULL,
  `st_bonds_payable` double DEFAULT NULL,
  `payable_to_reinsurer` double DEFAULT NULL,
  `rsrv_insur_cont` double DEFAULT NULL,
  `acting_trading_sec` double DEFAULT NULL,
  `acting_uw_sec` double DEFAULT NULL,
  `non_cur_liab_due_1y` double DEFAULT NULL,
  `oth_cur_liab` double DEFAULT NULL,
  `total_cur_liab` double DEFAULT NULL,
  `bond_payable` double DEFAULT NULL,
  `lt_payable` double DEFAULT NULL,
  `specific_payables` double DEFAULT NULL,
  `estimated_liab` double DEFAULT NULL,
  `defer_tax_liab` double DEFAULT NULL,
  `defer_inc_non_cur_liab` double DEFAULT NULL,
  `oth_ncl` double DEFAULT NULL,
  `total_ncl` double DEFAULT NULL,
  `depos_oth_bfi` double DEFAULT NULL,
  `deriv_liab` double DEFAULT NULL,
  `depos` double DEFAULT NULL,
  `agency_bus_liab` double DEFAULT NULL,
  `oth_liab` double DEFAULT NULL,
  `prem_receiv_adva` double DEFAULT NULL,
  `depos_received` double DEFAULT NULL,
  `ph_invest` double DEFAULT NULL,
  `reser_une_prem` double DEFAULT NULL,
  `reser_outstd_claims` double DEFAULT NULL,
  `reser_lins_liab` double DEFAULT NULL,
  `reser_lthins_liab` double DEFAULT NULL,
  `indept_acc_liab` double DEFAULT NULL,
  `pledge_borr` double DEFAULT NULL,
  `indem_payable` double DEFAULT NULL,
  `policy_div_payable` double DEFAULT NULL,
  `total_liab` double DEFAULT NULL,
  `treasury_share` double DEFAULT NULL,
  `ordin_risk_reser` double DEFAULT NULL,
  `forex_differ` double DEFAULT NULL,
  `invest_loss_unconf` double DEFAULT NULL,
  `minority_int` double DEFAULT NULL,
  `total_hldr_eqy_exc_min_int` double DEFAULT NULL,
  `total_hldr_eqy_inc_min_int` double DEFAULT NULL,
  `total_liab_hldr_eqy` double DEFAULT NULL,
  `lt_payroll_payable` double DEFAULT NULL,
  `oth_comp_income` double DEFAULT NULL,
  `oth_eqt_tools` double DEFAULT NULL,
  `oth_eqt_tools_p_shr` double DEFAULT NULL,
  `lending_funds` double DEFAULT NULL,
  `acc_receivable` double DEFAULT NULL,
  `st_fin_payable` double DEFAULT NULL,
  `payables` double DEFAULT NULL,
  `hfs_assets` double DEFAULT NULL,
  `hfs_sales` double DEFAULT NULL,
  UNIQUE KEY `idx_balance_end_date_ts_code_report_type` (`ts_code`,`end_date`,`report_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- create cashflow table
CREATE TABLE `cashflow` (
	`ts_code` varchar(20),
	`ann_date` varchar(20),
	`f_ann_date` varchar(20),
	`end_date` varchar(20),
	`comp_type` varchar(10),
	`report_type` varchar(10),
	`net_profit` double DEFAULT NULL,
	`finan_exp` double DEFAULT NULL,
	`c_fr_sale_sg` double DEFAULT NULL,
	`recp_tax_rends` double DEFAULT NULL,
	`n_depos_incr_fi` double DEFAULT NULL,
	`n_incr_loans_cb` double DEFAULT NULL,
	`n_inc_borr_oth_fi` double DEFAULT NULL,
	`prem_fr_orig_contr` double DEFAULT NULL,
	`n_incr_insured_dep` double DEFAULT NULL,
	`n_reinsur_prem` double DEFAULT NULL,
	`n_incr_disp_tfa` double DEFAULT NULL,
	`ifc_cash_incr` double DEFAULT NULL,
	`n_incr_disp_faas` double DEFAULT NULL,
	`n_incr_loans_oth_bank` double DEFAULT NULL,
	`n_cap_incr_repur` double DEFAULT NULL,
	`c_fr_oth_operate_a` double DEFAULT NULL,
	`c_inf_fr_operate_a` double DEFAULT NULL,
	`c_paid_goods_s` double DEFAULT NULL,
	`c_paid_to_for_empl` double DEFAULT NULL,
	`c_paid_for_taxes` double DEFAULT NULL,
	`n_incr_clt_loan_adv` double DEFAULT NULL,
	`n_incr_dep_cbob` double DEFAULT NULL,
	`c_pay_claims_orig_inco` double DEFAULT NULL,
	`pay_handling_chrg` double DEFAULT NULL,
	`pay_comm_insur_plcy` double DEFAULT NULL,
	`oth_cash_pay_oper_act` double DEFAULT NULL,
	`st_cash_out_act` double DEFAULT NULL,
	`n_cashflow_act` double DEFAULT NULL,
	`oth_recp_ral_inv_act` double DEFAULT NULL,
	`c_disp_withdrwl_invest` double DEFAULT NULL,
	`c_recp_return_invest` double DEFAULT NULL,
	`n_recp_disp_fiolta` double DEFAULT NULL,
	`n_recp_disp_sobu` double DEFAULT NULL,
	`stot_inflows_inv_act` double DEFAULT NULL,
	`c_pay_acq_const_fiolta` double DEFAULT NULL,
	`c_paid_invest` double DEFAULT NULL,
	`n_disp_subs_oth_biz` double DEFAULT NULL,
	`oth_pay_ral_inv_act` double DEFAULT NULL,
	`n_incr_pledge_loan` double DEFAULT NULL,
	`stot_out_inv_act` double DEFAULT NULL,
	`n_cashflow_inv_act` double DEFAULT NULL,
	`c_recp_borrow` double DEFAULT NULL,
	`proc_issue_bonds` double DEFAULT NULL,
	`oth_cash_recp_ral_fnc_act` double DEFAULT NULL,
	`stot_cash_in_fnc_act` double DEFAULT NULL,
	`free_cashflow` double DEFAULT NULL,
	`c_prepay_amt_borr` double DEFAULT NULL,
	`c_pay_dist_dpcp_int_exp` double DEFAULT NULL,
	`incl_dvd_profit_paid_sc_ms` double DEFAULT NULL,
	`oth_cashpay_ral_fnc_act` double DEFAULT NULL,
	`stot_cashout_fnc_act` double DEFAULT NULL,
	`n_cash_flows_fnc_act` double DEFAULT NULL,
	`eff_fx_flu_cash` double DEFAULT NULL,
	`n_incr_cash_cash_equ` double DEFAULT NULL,
	`c_cash_equ_beg_period` double DEFAULT NULL,
	`c_cash_equ_end_period` double DEFAULT NULL,
	`c_recp_cap_contrib` double DEFAULT NULL,
	`incl_cash_rec_saims` double DEFAULT NULL,
	`uncon_invest_loss` double DEFAULT NULL,
	`prov_depr_assets` double DEFAULT NULL,
	`depr_fa_coga_dpba` double DEFAULT NULL,
	`amort_intang_assets` double DEFAULT NULL,
	`lt_amort_deferred_exp` double DEFAULT NULL,
	`decr_deferred_exp` double DEFAULT NULL,
	`incr_acc_exp` double DEFAULT NULL,
	`loss_disp_fiolta` double DEFAULT NULL,
	`loss_scr_fa` double DEFAULT NULL,
	`loss_fv_chg` double DEFAULT NULL,
	`invest_loss` double DEFAULT NULL,
	`decr_def_inc_tax_assets` double DEFAULT NULL,
	`incr_def_inc_tax_liab` double DEFAULT NULL,
	`decr_inventories` double DEFAULT NULL,
	`decr_oper_payable` double DEFAULT NULL,
	`incr_oper_payable` double DEFAULT NULL,
	`others` double DEFAULT NULL,
	`im_net_cashflow_oper_act` double DEFAULT NULL,
	`conv_debt_into_cap` double DEFAULT NULL,
	`conv_copbonds_due_within_1y` double DEFAULT NULL,
	`fa_fnc_leases` double DEFAULT NULL,
	`end_bal_cash` double DEFAULT NULL,
	`beg_bal_cash` double DEFAULT NULL,
	`end_bal_cash_equ` double DEFAULT NULL,
	`beg_bal_cash_equ` double DEFAULT NULL,
	`im_n_incr_cash_equ` double DEFAULT NULL,
  UNIQUE KEY `idx_cashflow_end_date_ts_code_report_type` (`ts_code`,`end_date`,`report_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- create finance indicators table
CREATE TABLE `finance` (
  `ts_code` varchar(20),
  `end_date` varchar(20),
  `ann_date` varchar(20),
  `eps` double DEFAULT NULL,
  `dt_eps` double DEFAULT NULL,
  `total_revenue_ps` double DEFAULT NULL,
  `revenue_ps` double DEFAULT NULL,
  `capital_rese_ps` double DEFAULT NULL,
  `surplus_rese_ps` double DEFAULT NULL,
  `undist_profit_ps` double DEFAULT NULL,
  `extra_item` double DEFAULT NULL,
  `profit_dedt` double DEFAULT NULL,
  `gross_margin` double DEFAULT NULL,
  `current_ratio` double DEFAULT NULL,
  `quick_ratio` double DEFAULT NULL,
  `cash_ratio` double DEFAULT NULL,
  `ar_turn` double DEFAULT NULL,
  `ca_turn` double DEFAULT NULL,
  `fa_turn` double DEFAULT NULL,
  `assets_turn` double DEFAULT NULL,
  `op_income` double DEFAULT NULL,
  `ebit` double DEFAULT NULL,
  `ebitda` double DEFAULT NULL,
  `fcff` double DEFAULT NULL,
  `fcfe` double DEFAULT NULL,
  `current_exint` double DEFAULT NULL,
  `noncurrent_exint` double DEFAULT NULL,
  `interestdebt` double DEFAULT NULL,
  `netdebt` double DEFAULT NULL,
  `tangible_asset` double DEFAULT NULL,
  `working_capital` double DEFAULT NULL,
  `networking_capital` double DEFAULT NULL,
  `invest_capital` double DEFAULT NULL,
  `retained_earnings` double DEFAULT NULL,
  `diluted2_eps` double DEFAULT NULL,
  `bps` double DEFAULT NULL,
  `ocfps` double DEFAULT NULL,
  `retainedps` double DEFAULT NULL,
  `cfps` double DEFAULT NULL,
  `ebit_ps` double DEFAULT NULL,
  `fcff_ps` double DEFAULT NULL,
  `fcfe_ps` double DEFAULT NULL,
  `netprofit_margin` double DEFAULT NULL,
  `grossprofit_margin` double DEFAULT NULL,
  `cogs_of_sales` double DEFAULT NULL,
  `expense_of_sales` double DEFAULT NULL,
  `profit_to_gr` double DEFAULT NULL,
  `saleexp_to_gr` double DEFAULT NULL,
  `adminexp_of_gr` double DEFAULT NULL,
  `finaexp_of_gr` double DEFAULT NULL,
  `impai_ttm` double DEFAULT NULL,
  `gc_of_gr` double DEFAULT NULL,
  `op_of_gr` double DEFAULT NULL,
  `ebit_of_gr` double DEFAULT NULL,
  `roe` double DEFAULT NULL,
  `roe_waa` double DEFAULT NULL,
  `roe_dt` double DEFAULT NULL,
  `roa` double DEFAULT NULL,
  `npta` double DEFAULT NULL,
  `roic` double DEFAULT NULL,
  `roe_yearly` double DEFAULT NULL,
  `roa2_yearly` double DEFAULT NULL,
  `debt_to_assets` double DEFAULT NULL,
  `assets_to_eqt` double DEFAULT NULL,
  `dp_assets_to_eqt` double DEFAULT NULL,
  `ca_to_assets` double DEFAULT NULL,
  `nca_to_assets` double DEFAULT NULL,
  `tbassets_to_totalassets` double DEFAULT NULL,
  `int_to_talcap` double DEFAULT NULL,
  `eqt_to_talcapital` double DEFAULT NULL,
  `currentdebt_to_debt` double DEFAULT NULL,
  `longdeb_to_debt` double DEFAULT NULL,
  `ocf_to_shortdebt` double DEFAULT NULL,
  `debt_to_eqt` double DEFAULT NULL,
  `eqt_to_debt` double DEFAULT NULL,
  `eqt_to_interestdebt` double DEFAULT NULL,
  `tangibleasset_to_debt` double DEFAULT NULL,
  `tangasset_to_intdebt` double DEFAULT NULL,
  `tangibleasset_to_netdebt` double DEFAULT NULL,
  `ocf_to_debt` double DEFAULT NULL,
  `turn_days` double DEFAULT NULL,
  `roa_yearly` double DEFAULT NULL,
  `roa_dp` double DEFAULT NULL,
  `fixed_assets` double DEFAULT NULL,
  `profit_to_op` double DEFAULT NULL,
  `q_saleexp_to_gr` double DEFAULT NULL,
  `q_gc_to_gr` double DEFAULT NULL,
  `q_roe` double DEFAULT NULL,
  `q_dt_roe` double DEFAULT NULL,
  `q_npta` double DEFAULT NULL,
  `q_ocf_to_sales` double DEFAULT NULL,
  `basic_eps_yoy` double DEFAULT NULL,
  `dt_eps_yoy` double DEFAULT NULL,
  `cfps_yoy` double DEFAULT NULL,
  `op_yoy` double DEFAULT NULL,
  `ebt_yoy` double DEFAULT NULL,
  `netprofit_yoy` double DEFAULT NULL,
  `dt_netprofit_yoy` double DEFAULT NULL,
  `ocf_yoy` double DEFAULT NULL,
  `roe_yoy` double DEFAULT NULL,
  `bps_yoy` double DEFAULT NULL,
  `assets_yoy` double DEFAULT NULL,
  `eqt_yoy` double DEFAULT NULL,
  `tr_yoy` double DEFAULT NULL,
  `or_yoy` double DEFAULT NULL,
  `q_sales_yoy` double DEFAULT NULL,
  `q_op_qoq` double DEFAULT NULL,
  `equity_yoy` double DEFAULT NULL,
  UNIQUE KEY `idx_cashflow_end_date_ts_code` (`ts_code`,`end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- create main_business table
CREATE TABLE `mainbusiness` (
  `ts_code` varchar(20),
  `end_date` varchar(20),
  `bz_item` varchar(200),
  `type` varchar(10),
  `bz_sales` double DEFAULT NULL,
  `bz_profit` double DEFAULT NULL,
  `bz_cost` double DEFAULT NULL,
  `curr_type` varchar(10),
  UNIQUE KEY `idx_mainbusiness_end_date_ts_code_type` (`ts_code`,`end_date`, `type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- create adjust factor table
CREATE TABLE `adjustfactor` (
  `ts_code` varchar(20),
  `trade_date` varchar(20),
  `adj_factor` double DEFAULT NULL,
  UNIQUE KEY `idx_adjustfactor_trade_date_ts_code` (`ts_code`,`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `hkstockdata` (
  `ts_code` varchar(20) DEFAULT NULL,
  `name` varchar(20) DEFAULT NULL,
  `fullname` text,
  `enname` text,
  `cn_spell` varchar(20) DEFAULT NULL,
  `market` varchar(20) DEFAULT NULL,
  `list_status` varchar(20) DEFAULT NULL,
  `list_date` varchar(20) DEFAULT NULL,
  `delist_date` varchar(20) DEFAULT NULL,
  `trade_unit` double DEFAULT NULL,
  `isin` varchar(20) DEFAULT NULL,
  `curr_type` varchar(20) DEFAULT NULL,
  UNIQUE KEY `idx_hkdaily_ts_code` (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `hkdaily` (
  `ts_code` varchar(20),
  `trade_date` varchar(20),
  `open` double DEFAULT NULL,
  `high` double DEFAULT NULL,
  `low` double DEFAULT NULL,
  `close` double DEFAULT NULL,
  `pre_close` double DEFAULT NULL,
  `change` double DEFAULT NULL,
  `pct_chg` double DEFAULT NULL,
  `vol` double DEFAULT NULL,
  `amount` double DEFAULT NULL,
  unique KEY `ix_hkdaily_ts_code` (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


----------------------------------------------------------------------------
create database indexdata; 
use indexdata; 

CREATE TABLE `indexdata` (
  `ts_code` varchar(20),
  `name` text,
  `market` text,
  `publisher` text,
  `category` text,
  `base_date` text,
  `base_point` double DEFAULT NULL,
  `list_date` text,
  UNIQUE KEY `idx_indexdata_ts_code` (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `weight` (
  `index_code` varchar(20),
  `con_code` varchar(20),
  `trade_date` varchar(20),
  `weight` double DEFAULT NULL,
  UNIQUE KEY `idx_weight_index_code_con_code_trade_date` (`index_code`,`con_code`, `trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `dailybasic` (
  `ts_code` varchar(20),
  `trade_date` varchar(20),
  `total_mv` double DEFAULT NULL,
  `float_mv` double DEFAULT NULL,
  `total_share` double DEFAULT NULL,
  `float_share` double DEFAULT NULL,
  `free_share` double DEFAULT NULL,
  `turnover_rate` double DEFAULT NULL,
  `turnover_rate_f` double DEFAULT NULL,
  `pe` double DEFAULT NULL,
  `pe_ttm` double DEFAULT NULL,
  `pb` double DEFAULT NULL, 
  UNIQUE KEY `idx_indexdata_ts_code_trade_date` (`ts_code`, `trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-------------------------------------------------------------------------------
create database usstock; 
use usstock; 

CREATE TABLE `stocklist` (
  `ts_code` varchar(20),
  `name` varchar(40),
  `classify` varchar(20),
  `list_date` varchar(20),
  `delist_date` varchar(20),
  UNIQUE KEY `idx_indexdata_ts_code` (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create database fund; 
use fund; 

CREATE TABLE `fundlist` (
  `ts_code` varchar(20),
  `name` text,
  `management` text,
  `custodian` text,
  `fund_type` text,
  `found_date` text,
  `due_date` text,
  `list_date` text,
  `issue_date` text,
  `delist_date` text,
  `issue_amount` double DEFAULT NULL,
  `m_fee` double DEFAULT NULL,
  `c_fee` double DEFAULT NULL,
  `duration_year` double DEFAULT NULL,
  `p_value` double DEFAULT NULL,
  `min_amount` double DEFAULT NULL,
  `exp_return` text,
  `benchmark` text,
  `status` text,
  `invest_type` text,
  `type` text,
  `trustee` text,
  `purc_startdate` text,
  `redm_startdate` text,
  `market` text,
  UNIQUE KEY `ix_fundlist_index` (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `company` (
  `index` bigint DEFAULT NULL,
  `name` text,
  `shortname` text,
  `province` text,
  `city` text,
  `address` text,
  `phone` text,
  `office` text,
  `website` text,
  `chairman` text,
  `manager` text,
  `reg_capital` double DEFAULT NULL,
  `setup_date` text,
  `end_date` text,
  `employees` double DEFAULT NULL,
  `main_business` text,
  `org_code` text,
  `credit_code` text,
  UNIQUE KEY `ix_company_index` (`index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `manager` (
  `ts_code` varchar(20),
  `name` varchar(20),
  `ann_date` varchar(20),
  `gender` varchar(10),
  `birth_year` varchar(20),
  `edu` varchar(20),
  `nationality` varchar(20),
  `begin_date` varchar(20),
  `end_date` varchar(20),
  `resume` text, 
  UNIQUE KEY `idx_manager_ts_code` (`ts_code`, `name`, `ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `share` (
  `ts_code` varchar(20),
  `trade_date` varchar(20),
  `fd_share` double DEFAULT NULL,
  `fund_type` varchar(10),
  `market` varchar(10),
  UNIQUE KEY `idx_share_ts_code_trade_date` (`ts_code`, `trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `nav` (
  `ts_code` varchar(20),
  `end_date` varchar(20),
  `ann_date` varchar(20),
  `unit_nav` double DEFAULT NULL,
  `accum_nav` double DEFAULT NULL,
  `accum_div` varchar(20),
  `net_asset` double DEFAULT NULL,
  `total_netasset` double DEFAULT NULL,
  `adj_nav` double DEFAULT NULL,
  `update_flag` varchar(20),
  UNIQUE KEY `idx_nav_ts_code_end_date_adj_nav` (`ts_code`, `end_date`, `adj_nav`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `dividend` (
  `ts_code` varchar(20),
  `ann_date` varchar(20),
  `imp_anndate` varchar(20),
  `base_date` varchar(20),
  `div_proc` varchar(20),
  `record_date` varchar(20),
  `ex_date` varchar(20),
  `pay_date` varchar(20),
  `earpay_date` varchar(20),
  `net_ex_date` varchar(20),
  `div_cash` double DEFAULT NULL,
  `base_unit` double DEFAULT NULL,
  `ear_distr` double DEFAULT NULL,
  `ear_amount` double DEFAULT NULL,
  `account_date` varchar(20),
  `base_year` varchar(20),
  UNIQUE KEY `idx_dividend_ts_code_ann_date` (`ts_code`, `ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `portfolio` (
  `ts_code` varchar(20),
  `ann_date` varchar(20),
  `symbol` varchar(20),
  `end_date` varchar(20),
  `mkv` double DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `stk_mkv_ratio` double DEFAULT NULL,
  `stk_float_ratio` double DEFAULT NULL,
  UNIQUE KEY `idx_portfolio_ts_code_ann_date_symbol` (`ts_code`, `ann_date`, `symbol`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `daily` (
  `ts_code` varchar(20),
  `trade_date` varchar(20),
  `pre_close` double DEFAULT NULL,
  `open` double DEFAULT NULL,
  `high` double DEFAULT NULL,
  `low` double DEFAULT NULL,
  `close` double DEFAULT NULL,
  `change` double DEFAULT NULL,
  `pct_chg` double DEFAULT NULL,
  `vol` double DEFAULT NULL,
  `amount` double DEFAULT NULL,
  KEY `idx_daily_ts_code_tradedate` (`ts_code`, `trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `adjust` (
  `ts_code` varchar(20),
  `trade_date` varchar(20),
  `adj_factor` double DEFAULT NULL,
  KEY `idx_adjust_ts_code_trade_date` (`ts_code`, `trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



create database macro; 
use macro; 

CREATE TABLE `shibor` (
  `date` varchar(20),
  `on` double DEFAULT NULL,
  `1w` double DEFAULT NULL,
  `2w` double DEFAULT NULL,
  `1m` double DEFAULT NULL,
  `3m` double DEFAULT NULL,
  `6m` double DEFAULT NULL,
  `9m` double DEFAULT NULL,
  `1y` double DEFAULT NULL,
  unique KEY `idx_shibor_date` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `shiborquote` (
  `date` varchar(20),
  `bank` varchar(40),
  `on_b` double DEFAULT NULL,
  `on_a` double DEFAULT NULL,
  `1w_b` double DEFAULT NULL,
  `1w_a` double DEFAULT NULL,
  `2w_b` double DEFAULT NULL,
  `2w_a` double DEFAULT NULL,
  `1m_b` double DEFAULT NULL,
  `1m_a` double DEFAULT NULL,
  `3m_b` double DEFAULT NULL,
  `3m_a` double DEFAULT NULL,
  `6m_b` double DEFAULT NULL,
  `6m_a` double DEFAULT NULL,
  `9m_b` double DEFAULT NULL,
  `9m_a` double DEFAULT NULL,
  `1y_b` double DEFAULT NULL,
  `1y_a` double DEFAULT NULL,
  unique KEY `idx_shiborquote_date` (`date`, `bank`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `shiborlpr` (
  `date` varchar(20),
  `1y` double DEFAULT NULL,
  unique KEY `idx_shiborlpr_date` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `libor` (
  `date` varchar(20),
  `curr_type` varchar(20),
  `on` double DEFAULT NULL,
  `1w` double DEFAULT NULL,
  `1m` double DEFAULT NULL,
  `2m` double DEFAULT NULL,
  `3m` double DEFAULT NULL,
  `6m` double DEFAULT NULL,
  `12m` double DEFAULT NULL,
  KEY `idx_libor_date_curr_type` (`date`, `curr_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `hibor` (
  `date` varchar(20),
  `on` double DEFAULT NULL,
  `1w` double DEFAULT NULL,
  `2w` double DEFAULT NULL,
  `1m` double DEFAULT NULL,
  `2m` double DEFAULT NULL,
  `3m` double DEFAULT NULL,
  `6m` double DEFAULT NULL,
  `12m` double DEFAULT NULL,
  KEY `idx_hibor_date` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `wzindex` (
  `date` varchar(20),
  `comp_rate` double DEFAULT NULL,
  `center_rate` double DEFAULT NULL,
  `micro_rate` double DEFAULT NULL,
  `cm_rate` double DEFAULT NULL,
  `sdb_rate` double DEFAULT NULL,
  `om_rate` double DEFAULT NULL,
  `aa_rate` double DEFAULT NULL,
  `m1_rate` double DEFAULT NULL,
  `m3_rate` double DEFAULT NULL,
  `m6_rate` double DEFAULT NULL,
  `m12_rate` double DEFAULT NULL,
  `long_rate` double DEFAULT NULL,
  KEY `idx_wzindex_date` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `gzindex` (
  `date` varchar(20),
  `d10_rate` double DEFAULT NULL,
  `m1_rate` double DEFAULT NULL,
  `m3_rate` double DEFAULT NULL,
  `m6_rate` double DEFAULT NULL,
  `m12_rate` double DEFAULT NULL,
  `long_rate` double DEFAULT NULL,
  KEY `idx_gzindex_date` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `exchangedata` (
  `ts_code` varchar(20),
  `name` varchar(40),
  `classify` varchar(20),
  `exchange` varchar(20),
  `min_unit` double DEFAULT NULL,
  `max_unit` double DEFAULT NULL,
  `pip` double DEFAULT NULL,
  `pip_cost` double DEFAULT NULL,
  `traget_spread` double DEFAULT NULL,
  `min_stop_distance` double DEFAULT NULL,
  `trading_hours` varchar(100),
  `break_time` varchar(100),
  UNIQUE KEY `idx_exchangedata_ts_code` (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `fxdaily` (
  `ts_code` varchar(20),
  `trade_date` varchar(20),
  `bid_open` double DEFAULT NULL,
  `bid_close` double DEFAULT NULL,
  `bid_high` double DEFAULT NULL,
  `bid_low` double DEFAULT NULL,
  `ask_open` double DEFAULT NULL,
  `ask_close` double DEFAULT NULL,
  `ask_high` double DEFAULT NULL,
  `ask_low` double DEFAULT NULL,
  `tick_qty` bigint DEFAULT NULL,
  unique KEY `ix_fxdaily_ts_code_trade_date` (`ts_code`, `trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


create database usstock; 
use usstock; 

CREATE TABLE `daily` (
  `ts_code` varchar(20), 
  `trade_date` varchar(20),
  `volume` bigint DEFAULT NULL,
  `open` double DEFAULT NULL,
  `high` double DEFAULT NULL,
  `low` double DEFAULT NULL,
  `close` double DEFAULT NULL,
  `chg` double DEFAULT NULL,
  `percent` double DEFAULT NULL,
  `turnoverrate` double DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `pe` double DEFAULT NULL,
  `pb` double DEFAULT NULL,
  `ps` double DEFAULT NULL,
  `pcf` double DEFAULT NULL,
  `market_capital` double DEFAULT NULL,
  UNIQUE KEY `ix_daily_ts_code_trade_date` (`ts_code`, `trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cashflowbase` (
  `ts_code` varchar(20),
  `annual_settle_date` varchar(20) default null,
  `currency` varchar(20) default null,
  `currency_name` varchar(20) default null,
  `last_report_name` varchar(40) default null,
  `org_type` int DEFAULT 1,
  `quote_name` varchar(200) DEFAULT NULL,
  `sas` text,
  `statuses` varchar(20) DEFAULT NULL,
  `tip` text,
  UNIQUE KEY `idx_cashflowbase_ts_code` (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `cashflow` (
  `ts_code` varchar(20),
  `report_date` bigint DEFAULT NULL,
  `report_name` varchar(40) DEFAULT NULL,
  `ctime` varchar(20) DEFAULT NULL,
  `report_type_code` bigint DEFAULT NULL,
  `report_annual` bigint DEFAULT NULL,
  `sd` varchar(20) DEFAULT NULL,
  `ed` varchar(20) DEFAULT NULL,
  `net_cash_provided_by_oa` double DEFAULT NULL,
  `net_cash_provided_by_oa_rate` double DEFAULT NULL,
  `net_cash_used_in_ia` double DEFAULT NULL,
  `net_cash_used_in_ia_rate` double DEFAULT NULL,
  `net_cash_used_in_fa` double DEFAULT NULL,
  `net_cash_used_in_fa_rate` double DEFAULT NULL,
  `payment_for_property_and_equip` double DEFAULT NULL,
  `payment_for_property_and_equip_rate` double DEFAULT NULL,
  `effect_of_exchange_chg_on_cce` double DEFAULT NULL,
  `effect_of_exchange_chg_on_cce_rate` double DEFAULT NULL,
  `cce_at_boy` double DEFAULT NULL,
  `cce_at_boy_rate` double DEFAULT NULL,
  `cce_at_eoy` double DEFAULT NULL,
  `cce_at_eoy_rate` double DEFAULT NULL,
  `increase_in_cce` double DEFAULT NULL,
  `increase_in_cce_rate` double DEFAULT NULL,
  `depreciation_and_amortization` double DEFAULT NULL,
  `depreciation_and_amortization_rate` double DEFAULT NULL,
  `operating_asset_and_liab_chg` double DEFAULT NULL,
  `operating_asset_and_liab_chg_rate` double DEFAULT NULL,
  `purs_of_invest` double DEFAULT NULL,
  `purs_of_invest_rate` double DEFAULT NULL,
  `common_stock_issue` double DEFAULT NULL,
  `common_stock_issue_rate` double DEFAULT NULL,
  `repur_of_common_stock` double DEFAULT NULL,
  `repur_of_common_stock_rate` double DEFAULT NULL,
  `dividend_paid` double DEFAULT NULL,
  `dividend_paid_rate` double DEFAULT NULL,
  unique KEY `ix_cashflow_ts_code_report_date` (`ts_code`, `report_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `incomebase` (
  `ts_code` varchar(20),
  `annual_settle_date` varchar(20) default null,
  `currency` varchar(20) default null,
  `currency_name` varchar(20) default null,
  `last_report_name` varchar(40) default null,
  `org_type` int DEFAULT 1,
  `quote_name` varchar(200) DEFAULT NULL,
  `sas` text,
  `statuses` varchar(20) DEFAULT NULL,
  `tip` text,
  UNIQUE KEY `idx_incomebase_ts_code` (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `income` (
  `ts_code` varchar(20),
  `report_date` bigint DEFAULT NULL,
  `report_name` varchar(40) DEFAULT NULL,
  `ctime` varchar(20) DEFAULT NULL,
  `report_type_code` bigint DEFAULT NULL,
  `report_annual` bigint DEFAULT NULL,
  `sd` varchar(20) DEFAULT NULL,
  `ed` varchar(20) DEFAULT NULL,
  `total_revenue` double DEFAULT NULL,
  `total_revenue_rate` double DEFAULT NULL,
  `income_from_co_before_it` double DEFAULT NULL,
  `income_from_co_before_it_rate` double DEFAULT NULL,
  `net_income_atcss` double DEFAULT NULL,
  `net_income_atcss_rate` double DEFAULT NULL,
  `income_from_co_before_tax_si` double DEFAULT NULL,
  `income_from_co_before_tax_si_rate` double DEFAULT NULL,
  `income_tax` double DEFAULT NULL,
  `income_tax_rate` double DEFAULT NULL,
  `income_from_co` double DEFAULT NULL,
  `income_from_co_rate` double DEFAULT NULL,
  `net_income` double DEFAULT NULL,
  `net_income_rate` double DEFAULT NULL,
  `preferred_dividend` double DEFAULT NULL,
  `preferred_dividend_rate` double DEFAULT NULL,
  `net_income_atms_interest` double DEFAULT NULL,
  `net_income_atms_interest_rate` double DEFAULT NULL,
  `total_compre_income_atms` double DEFAULT NULL,
  `total_compre_income_atms_rate` double DEFAULT NULL,
  `total_compre_income_atcss` double DEFAULT NULL,
  `total_compre_income_atcss_rate` double DEFAULT NULL,
  `total_basic_earning_common_ps` double DEFAULT NULL,
  `total_basic_earning_common_ps_rate` double DEFAULT NULL,
  `total_dlt_earnings_common_ps` double DEFAULT NULL,
  `total_dlt_earnings_common_ps_rate` double DEFAULT NULL,
  `total_compre_income` double DEFAULT NULL,
  `total_compre_income_rate` double DEFAULT NULL,
  `total_net_income_atcss` double DEFAULT NULL,
  `total_net_income_atcss_rate` double DEFAULT NULL,
  `revenue` double DEFAULT NULL,
  `revenue_rate` double DEFAULT NULL,
  `othr_revenues` double DEFAULT NULL,
  `othr_revenues_rate` double DEFAULT NULL,
  `sales_cost` double DEFAULT NULL,
  `sales_cost_rate` double DEFAULT NULL,
  `gross_profit` double DEFAULT NULL,
  `gross_profit_rate` double DEFAULT NULL,
  `marketing_selling_etc` double DEFAULT NULL,
  `marketing_selling_etc_rate` double DEFAULT NULL,
  `rad_expenses` double DEFAULT NULL,
  `rad_expenses_rate` double DEFAULT NULL,
  `net_interest_expense` double DEFAULT NULL,
  `net_interest_expense_rate` double DEFAULT NULL,
  `interest_income` double DEFAULT NULL,
  `interest_income_rate` double DEFAULT NULL,
  `interest_expense` double DEFAULT NULL,
  `interest_expense_rate` double DEFAULT NULL,
  `total_operate_expenses_si` double DEFAULT NULL,
  `total_operate_expenses_si_rate` double DEFAULT NULL,
  `total_operate_expenses` double DEFAULT NULL,
  `total_operate_expenses_rate` double DEFAULT NULL,
  `operating_income` double DEFAULT NULL,
  `operating_income_rate` double DEFAULT NULL,
  `share_of_earnings_of_affiliate` double DEFAULT NULL,
  `share_of_earnings_of_affiliate_rate` double DEFAULT NULL,
  `preminum` double DEFAULT NULL,
  `preminum_rate` double DEFAULT NULL,
  `net_invest_income` double DEFAULT NULL,
  `net_invest_income_rate` double DEFAULT NULL,
  `net_invest_gains` double DEFAULT NULL,
  `net_invest_gains_rate` double DEFAULT NULL,
  `service_commi_and_fees` double DEFAULT NULL,
  `service_commi_and_fees_rate` double DEFAULT NULL,
  `total_revenue_special_subject` double DEFAULT NULL,
  `total_revenue_special_subject_rate` double DEFAULT NULL,
  `loss_and_loss_adjust_cost` double DEFAULT NULL,
  `loss_and_loss_adjust_cost_rate` double DEFAULT NULL,
  `policyholder_benefits_etc` double DEFAULT NULL,
  `policyholder_benefits_etc_rate` double DEFAULT NULL,
  `total_benefit_etc_si` double DEFAULT NULL,
  `total_benefit_etc_si_rate` double DEFAULT NULL,
  `total_benefit_claim_and_cost` double DEFAULT NULL,
  `total_benefit_claim_and_cost_rate` double DEFAULT NULL,
  `operating_expenses` double DEFAULT NULL,
  `operating_expenses_rate` double DEFAULT NULL,
  `depreciation_and_amortization` double DEFAULT NULL,
  `depreciation_and_amortization_rate` double DEFAULT NULL,
  `total_expense_special_subject` double DEFAULT NULL,
  `total_expense_special_subject_rate` double DEFAULT NULL,
  `total_expense` double DEFAULT NULL,
  `total_expense_rate` double DEFAULT NULL,
  `tech_communication_and_equip` double DEFAULT NULL,
  `tech_communication_and_equip_rate` double DEFAULT NULL,
  `net_occupancy` double DEFAULT NULL,
  `net_occupancy_rate` double DEFAULT NULL,
  `total_non_interest_cost_si` double DEFAULT NULL,
  `total_non_interest_cost_si_rate` double DEFAULT NULL,
  `total_non_interest_expense` double DEFAULT NULL,
  `total_non_interest_expense_rate` double DEFAULT NULL,
  `invest_banking` double DEFAULT NULL,
  `invest_banking_rate` double DEFAULT NULL,
  `asset_manage_and_sec_services` double DEFAULT NULL,
  `asset_manage_and_sec_services_rate` double DEFAULT NULL,
  `compen_and_benefit` double DEFAULT NULL,
  `compen_and_benefit_rate` double DEFAULT NULL,
  `advertising_and_marketing` double DEFAULT NULL,
  `advertising_and_marketing_rate` double DEFAULT NULL,
  `loan_and_lease` double DEFAULT NULL,
  `loan_and_lease_rate` double DEFAULT NULL,
  `sec` double DEFAULT NULL,
  `sec_rate` double DEFAULT NULL,
  `td_assets` double DEFAULT NULL,
  `td_assets_rate` double DEFAULT NULL,
  `total_interest_income_si` double DEFAULT NULL,
  `total_interest_income_si_rate` double DEFAULT NULL,
  `total_interest_income` double DEFAULT NULL,
  `total_interest_income_rate` double DEFAULT NULL,
  `deposit` double DEFAULT NULL,
  `deposit_rate` double DEFAULT NULL,
  `st_borrowing` double DEFAULT NULL,
  `st_borrowing_rate` double DEFAULT NULL,
  `lt_debt` double DEFAULT NULL,
  `lt_debt_rate` double DEFAULT NULL,
  `td_liab` double DEFAULT NULL,
  `td_liab_rate` double DEFAULT NULL,
  `total_interest_expense_si` double DEFAULT NULL,
  `total_interest_expense_si_rate` double DEFAULT NULL,
  `total_interest_expense` double DEFAULT NULL,
  `total_interest_expense_rate` double DEFAULT NULL,
  `net_interest_income` double DEFAULT NULL,
  `net_interest_income_rate` double DEFAULT NULL,
  `commission` double DEFAULT NULL,
  `commission_rate` double DEFAULT NULL,
  `cerdit_card_income` double DEFAULT NULL,
  `cerdit_card_income_rate` double DEFAULT NULL,
  `service_charge` double DEFAULT NULL,
  `service_charge_rate` double DEFAULT NULL,
  `sec_gain` double DEFAULT NULL,
  `sec_gain_rate` double DEFAULT NULL,
  `insurance_income` double DEFAULT NULL,
  `insurance_income_rate` double DEFAULT NULL,
  `td_activity` double DEFAULT NULL,
  `td_activity_rate` double DEFAULT NULL,
  `total_non_interest_income_si` double DEFAULT NULL,
  `total_non_interest_income_si_rate` double DEFAULT NULL,
  `total_non_interest_income` double DEFAULT NULL,
  `total_non_interest_income_rate` double DEFAULT NULL,
  `salaries_and_employee_benefits` double DEFAULT NULL,
  `salaries_and_employee_benefits_rate` double DEFAULT NULL,
  `provision_for_credit_loss` double DEFAULT NULL,
  `provision_for_credit_loss_rate` double DEFAULT NULL,
  unique KEY `ix_income_ts_code_report_date` (`ts_code`, `report_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `balancebase` (
  `ts_code` varchar(20),
  `annual_settle_date` varchar(20) default null,
  `currency` varchar(20) default null,
  `currency_name` varchar(20) default null,
  `last_report_name` varchar(40) default null,
  `org_type` int DEFAULT 1,
  `quote_name` varchar(200) DEFAULT NULL,
  `sas` text,
  `statuses` varchar(20) DEFAULT NULL,
  `tip` text,
  UNIQUE KEY `idx_balancebase_ts_code` (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `balance` (
  `ts_code` varchar(20),
  `report_date` bigint DEFAULT NULL,
  `report_name` varchar(40) DEFAULT NULL,
  `ctime` varchar(20) DEFAULT NULL,
  `report_type_code` bigint DEFAULT NULL,
  `report_annual` bigint DEFAULT NULL,
  `sd` varchar(20) DEFAULT NULL,
  `ed` varchar(20) DEFAULT NULL,
  `total_assets` double DEFAULT NULL,
  `total_assets_rate` double DEFAULT NULL,
  `total_liab` double DEFAULT NULL,
  `total_liab_rate` double DEFAULT NULL,
  `asset_liab_ratio` double DEFAULT NULL,
  `asset_liab_ratio_rate` double DEFAULT NULL,
  `net_property_plant_and_equip` double DEFAULT NULL,
  `net_property_plant_and_equip_rate` double DEFAULT NULL,
  `total_assets_special_subject` double DEFAULT NULL,
  `total_assets_special_subject_rate` double DEFAULT NULL,
  `lt_debt` double DEFAULT NULL,
  `lt_debt_rate` double DEFAULT NULL,
  `total_liab_si` double DEFAULT NULL,
  `total_liab_si_rate` double DEFAULT NULL,
  `preferred_stock` double DEFAULT NULL,
  `preferred_stock_rate` double DEFAULT NULL,
  `common_stock` double DEFAULT NULL,
  `common_stock_rate` double DEFAULT NULL,
  `add_paid_in_capital` double DEFAULT NULL,
  `add_paid_in_capital_rate` double DEFAULT NULL,
  `retained_earning` double DEFAULT NULL,
  `retained_earning_rate` double DEFAULT NULL,
  `treasury_stock` double DEFAULT NULL,
  `treasury_stock_rate` double DEFAULT NULL,
  `accum_othr_compre_income` double DEFAULT NULL,
  `accum_othr_compre_income_rate` double DEFAULT NULL,
  `total_holders_equity_si` double DEFAULT NULL,
  `total_holders_equity_si_rate` double DEFAULT NULL,
  `total_holders_equity` double DEFAULT NULL,
  `total_holders_equity_rate` double DEFAULT NULL,
  `minority_interest` double DEFAULT NULL,
  `minority_interest_rate` double DEFAULT NULL,
  `total_equity_special_subject` double DEFAULT NULL,
  `total_equity_special_subject_rate` double DEFAULT NULL,
  `total_equity` double DEFAULT NULL,
  `total_equity_rate` double DEFAULT NULL,
  `cce` double DEFAULT NULL,
  `cce_rate` double DEFAULT NULL,
  `st_invest` double DEFAULT NULL,
  `st_invest_rate` double DEFAULT NULL,
  `total_cash` double DEFAULT NULL,
  `total_cash_rate` double DEFAULT NULL,
  `net_receivables` double DEFAULT NULL,
  `net_receivables_rate` double DEFAULT NULL,
  `inventory` double DEFAULT NULL,
  `inventory_rate` double DEFAULT NULL,
  `dt_assets_current_assets` double DEFAULT NULL,
  `dt_assets_current_assets_rate` double DEFAULT NULL,
  `prepaid_expense` double DEFAULT NULL,
  `prepaid_expense_rate` double DEFAULT NULL,
  `current_assets_special_subject` double DEFAULT NULL,
  `current_assets_special_subject_rate` double DEFAULT NULL,
  `total_current_assets` double DEFAULT NULL,
  `total_current_assets_rate` double DEFAULT NULL,
  `gross_property_plant_and_equip` double DEFAULT NULL,
  `gross_property_plant_and_equip_rate` double DEFAULT NULL,
  `accum_depreciation` double DEFAULT NULL,
  `accum_depreciation_rate` double DEFAULT NULL,
  `equity_and_othr_invest` double DEFAULT NULL,
  `equity_and_othr_invest_rate` double DEFAULT NULL,
  `goodwill` double DEFAULT NULL,
  `goodwill_rate` double DEFAULT NULL,
  `net_intangible_assets` double DEFAULT NULL,
  `net_intangible_assets_rate` double DEFAULT NULL,
  `accum_amortization` double DEFAULT NULL,
  `accum_amortization_rate` double DEFAULT NULL,
  `dt_assets_noncurrent_assets` double DEFAULT NULL,
  `dt_assets_noncurrent_assets_rate` double DEFAULT NULL,
  `nca_si` double DEFAULT NULL,
  `nca_si_rate` double DEFAULT NULL,
  `total_noncurrent_assets` double DEFAULT NULL,
  `total_noncurrent_assets_rate` double DEFAULT NULL,
  `st_debt` double DEFAULT NULL,
  `st_debt_rate` double DEFAULT NULL,
  `accounts_payable` double DEFAULT NULL,
  `accounts_payable_rate` double DEFAULT NULL,
  `income_tax_payable` double DEFAULT NULL,
  `income_tax_payable_rate` double DEFAULT NULL,
  `accrued_liab` double DEFAULT NULL,
  `accrued_liab_rate` double DEFAULT NULL,
  `deferred_revenue_current_liab` double DEFAULT NULL,
  `deferred_revenue_current_liab_rate` double DEFAULT NULL,
  `current_liab_si` double DEFAULT NULL,
  `current_liab_si_rate` double DEFAULT NULL,
  `total_current_liab` double DEFAULT NULL,
  `total_current_liab_rate` double DEFAULT NULL,
  `deferred_tax_liab` double DEFAULT NULL,
  `deferred_tax_liab_rate` double DEFAULT NULL,
  `dr_noncurrent_liab` double DEFAULT NULL,
  `dr_noncurrent_liab_rate` double DEFAULT NULL,
  `noncurrent_liab_si` double DEFAULT NULL,
  `noncurrent_liab_si_rate` double DEFAULT NULL,
  `total_noncurrent_liab` double DEFAULT NULL,
  `total_noncurrent_liab_rate` double DEFAULT NULL,
  `loan` double DEFAULT NULL,
  `loan_rate` double DEFAULT NULL,
  `fixed_maturity_sec` double DEFAULT NULL,
  `fixed_maturity_sec_rate` double DEFAULT NULL,
  `equity_sec` double DEFAULT NULL,
  `equity_sec_rate` double DEFAULT NULL,
  `td_sec` double DEFAULT NULL,
  `td_sec_rate` double DEFAULT NULL,
  `othr_invest` double DEFAULT NULL,
  `othr_invest_rate` double DEFAULT NULL,
  `total_invest` double DEFAULT NULL,
  `total_invest_rate` double DEFAULT NULL,
  `accrued_invest_income` double DEFAULT NULL,
  `accrued_invest_income_rate` double DEFAULT NULL,
  `premiums_and_othr_receivables` double DEFAULT NULL,
  `premiums_and_othr_receivables_rate` double DEFAULT NULL,
  `rein_assets` double DEFAULT NULL,
  `rein_assets_rate` double DEFAULT NULL,
  `deferred_policy_obtain_cost` double DEFAULT NULL,
  `deferred_policy_obtain_cost_rate` double DEFAULT NULL,
  `di_tax` double DEFAULT NULL,
  `di_tax_rate` double DEFAULT NULL,
  `separate_account_assets` double DEFAULT NULL,
  `separate_account_assets_rate` double DEFAULT NULL,
  `futures_policy_benefits` double DEFAULT NULL,
  `futures_policy_benefits_rate` double DEFAULT NULL,
  `policyholder_funds` double DEFAULT NULL,
  `policyholder_funds_rate` double DEFAULT NULL,
  `unearned_premium` double DEFAULT NULL,
  `unearned_premium_rate` double DEFAULT NULL,
  `reinsurance_liab` double DEFAULT NULL,
  `reinsurance_liab_rate` double DEFAULT NULL,
  `tax_payable` double DEFAULT NULL,
  `tax_payable_rate` double DEFAULT NULL,
  `separate_account_liab` double DEFAULT NULL,
  `separate_account_liab_rate` double DEFAULT NULL,
  `receivable` double DEFAULT NULL,
  `receivable_rate` double DEFAULT NULL,
  `payable` double DEFAULT NULL,
  `payable_rate` double DEFAULT NULL,
  `st_borrowing` double DEFAULT NULL,
  `st_borrowing_rate` double DEFAULT NULL,
  `federal_funds_purd` double DEFAULT NULL,
  `federal_funds_purd_rate` double DEFAULT NULL,
  `td_liab` double DEFAULT NULL,
  `td_liab_rate` double DEFAULT NULL,
  `cash_and_due_from_banks` double DEFAULT NULL,
  `cash_and_due_from_banks_rate` double DEFAULT NULL,
  `deposits_with_banks` double DEFAULT NULL,
  `deposits_with_banks_rate` double DEFAULT NULL,
  `federal_funds_sold` double DEFAULT NULL,
  `federal_funds_sold_rate` double DEFAULT NULL,
  `td_assets` double DEFAULT NULL,
  `td_assets_rate` double DEFAULT NULL,
  `debt_sec` double DEFAULT NULL,
  `debt_sec_rate` double DEFAULT NULL,
  `allowance_for_loan_loss` double DEFAULT NULL,
  `allowance_for_loan_loss_rate` double DEFAULT NULL,
  `net_loan` double DEFAULT NULL,
  `net_loan_rate` double DEFAULT NULL,
  `mortgage_servicing_rights` double DEFAULT NULL,
  `mortgage_servicing_rights_rate` double DEFAULT NULL,
  `deposit` double DEFAULT NULL,
  `deposit_rate` double DEFAULT NULL,
  unique KEY `ix_balance_ts_code_report_date` (`ts_code`, `report_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `divident` (
  `ts_code` varchar(20),
  `announce_date` varchar(20) DEFAULT NULL,
  `explain` text,
  `dividend_date` varchar(20) DEFAULT NULL,
  `exright_date` varchar(20) DEFAULT NULL,
  `money` double DEFAULT NULL,
  `currency` varchar(20) DEFAULT NULL,
  unique KEY `ix_divident_ts_code_announce_date` (`ts_code`, `announce_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




